//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestockReport.BatchReport {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://secure.myterminals.com/BatchReportWebService", ConfigurationName="BatchReport.BatchReportServiceSoap")]
    public interface BatchReportServiceSoap {
        
        // CODEGEN: Generating message contract since element name ReportDate from namespace https://secure.myterminals.com/BatchReportWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.myterminals.com/BatchReportWebService/GetReportLength", ReplyAction="*")]
        RestockReport.BatchReport.GetReportLengthResponse GetReportLength(RestockReport.BatchReport.GetReportLengthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.myterminals.com/BatchReportWebService/GetReportLength", ReplyAction="*")]
        System.Threading.Tasks.Task<RestockReport.BatchReport.GetReportLengthResponse> GetReportLengthAsync(RestockReport.BatchReport.GetReportLengthRequest request);
        
        // CODEGEN: Generating message contract since element name ReportDate from namespace https://secure.myterminals.com/BatchReportWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.myterminals.com/BatchReportWebService/GetReportData", ReplyAction="*")]
        RestockReport.BatchReport.GetReportDataResponse GetReportData(RestockReport.BatchReport.GetReportDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.myterminals.com/BatchReportWebService/GetReportData", ReplyAction="*")]
        System.Threading.Tasks.Task<RestockReport.BatchReport.GetReportDataResponse> GetReportDataAsync(RestockReport.BatchReport.GetReportDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportLengthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportLength", Namespace="https://secure.myterminals.com/BatchReportWebService", Order=0)]
        public RestockReport.BatchReport.GetReportLengthRequestBody Body;
        
        public GetReportLengthRequest() {
        }
        
        public GetReportLengthRequest(RestockReport.BatchReport.GetReportLengthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://secure.myterminals.com/BatchReportWebService")]
    public partial class GetReportLengthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReportDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] PasswordHash;
        
        public GetReportLengthRequestBody() {
        }
        
        public GetReportLengthRequestBody(string ReportDate, string UserID, byte[] PasswordHash) {
            this.ReportDate = ReportDate;
            this.UserID = UserID;
            this.PasswordHash = PasswordHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportLengthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportLengthResponse", Namespace="https://secure.myterminals.com/BatchReportWebService", Order=0)]
        public RestockReport.BatchReport.GetReportLengthResponseBody Body;
        
        public GetReportLengthResponse() {
        }
        
        public GetReportLengthResponse(RestockReport.BatchReport.GetReportLengthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://secure.myterminals.com/BatchReportWebService")]
    public partial class GetReportLengthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetReportLengthResult;
        
        public GetReportLengthResponseBody() {
        }
        
        public GetReportLengthResponseBody(int GetReportLengthResult) {
            this.GetReportLengthResult = GetReportLengthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportData", Namespace="https://secure.myterminals.com/BatchReportWebService", Order=0)]
        public RestockReport.BatchReport.GetReportDataRequestBody Body;
        
        public GetReportDataRequest() {
        }
        
        public GetReportDataRequest(RestockReport.BatchReport.GetReportDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://secure.myterminals.com/BatchReportWebService")]
    public partial class GetReportDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReportDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] PasswordHash;
        
        public GetReportDataRequestBody() {
        }
        
        public GetReportDataRequestBody(string ReportDate, string UserID, byte[] PasswordHash) {
            this.ReportDate = ReportDate;
            this.UserID = UserID;
            this.PasswordHash = PasswordHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportDataResponse", Namespace="https://secure.myterminals.com/BatchReportWebService", Order=0)]
        public RestockReport.BatchReport.GetReportDataResponseBody Body;
        
        public GetReportDataResponse() {
        }
        
        public GetReportDataResponse(RestockReport.BatchReport.GetReportDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://secure.myterminals.com/BatchReportWebService")]
    public partial class GetReportDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetReportDataResult;
        
        public GetReportDataResponseBody() {
        }
        
        public GetReportDataResponseBody(byte[] GetReportDataResult) {
            this.GetReportDataResult = GetReportDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BatchReportServiceSoapChannel : RestockReport.BatchReport.BatchReportServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BatchReportServiceSoapClient : System.ServiceModel.ClientBase<RestockReport.BatchReport.BatchReportServiceSoap>, RestockReport.BatchReport.BatchReportServiceSoap {
        
        public BatchReportServiceSoapClient() {
        }
        
        public BatchReportServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BatchReportServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchReportServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchReportServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestockReport.BatchReport.GetReportLengthResponse RestockReport.BatchReport.BatchReportServiceSoap.GetReportLength(RestockReport.BatchReport.GetReportLengthRequest request) {
            return base.Channel.GetReportLength(request);
        }
        
        public int GetReportLength(string ReportDate, string UserID, byte[] PasswordHash) {
            RestockReport.BatchReport.GetReportLengthRequest inValue = new RestockReport.BatchReport.GetReportLengthRequest();
            inValue.Body = new RestockReport.BatchReport.GetReportLengthRequestBody();
            inValue.Body.ReportDate = ReportDate;
            inValue.Body.UserID = UserID;
            inValue.Body.PasswordHash = PasswordHash;
            RestockReport.BatchReport.GetReportLengthResponse retVal = ((RestockReport.BatchReport.BatchReportServiceSoap)(this)).GetReportLength(inValue);
            return retVal.Body.GetReportLengthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestockReport.BatchReport.GetReportLengthResponse> RestockReport.BatchReport.BatchReportServiceSoap.GetReportLengthAsync(RestockReport.BatchReport.GetReportLengthRequest request) {
            return base.Channel.GetReportLengthAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestockReport.BatchReport.GetReportLengthResponse> GetReportLengthAsync(string ReportDate, string UserID, byte[] PasswordHash) {
            RestockReport.BatchReport.GetReportLengthRequest inValue = new RestockReport.BatchReport.GetReportLengthRequest();
            inValue.Body = new RestockReport.BatchReport.GetReportLengthRequestBody();
            inValue.Body.ReportDate = ReportDate;
            inValue.Body.UserID = UserID;
            inValue.Body.PasswordHash = PasswordHash;
            return ((RestockReport.BatchReport.BatchReportServiceSoap)(this)).GetReportLengthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestockReport.BatchReport.GetReportDataResponse RestockReport.BatchReport.BatchReportServiceSoap.GetReportData(RestockReport.BatchReport.GetReportDataRequest request) {
            return base.Channel.GetReportData(request);
        }
        
        public byte[] GetReportData(string ReportDate, string UserID, byte[] PasswordHash) {
            RestockReport.BatchReport.GetReportDataRequest inValue = new RestockReport.BatchReport.GetReportDataRequest();
            inValue.Body = new RestockReport.BatchReport.GetReportDataRequestBody();
            inValue.Body.ReportDate = ReportDate;
            inValue.Body.UserID = UserID;
            inValue.Body.PasswordHash = PasswordHash;
            RestockReport.BatchReport.GetReportDataResponse retVal = ((RestockReport.BatchReport.BatchReportServiceSoap)(this)).GetReportData(inValue);
            return retVal.Body.GetReportDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestockReport.BatchReport.GetReportDataResponse> RestockReport.BatchReport.BatchReportServiceSoap.GetReportDataAsync(RestockReport.BatchReport.GetReportDataRequest request) {
            return base.Channel.GetReportDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestockReport.BatchReport.GetReportDataResponse> GetReportDataAsync(string ReportDate, string UserID, byte[] PasswordHash) {
            RestockReport.BatchReport.GetReportDataRequest inValue = new RestockReport.BatchReport.GetReportDataRequest();
            inValue.Body = new RestockReport.BatchReport.GetReportDataRequestBody();
            inValue.Body.ReportDate = ReportDate;
            inValue.Body.UserID = UserID;
            inValue.Body.PasswordHash = PasswordHash;
            return ((RestockReport.BatchReport.BatchReportServiceSoap)(this)).GetReportDataAsync(inValue);
        }
    }
}
