//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestockReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankAccountDetail
    {
        public int BankAccountId { get; set; }
        public int AccountTypeId { get; set; }
        public string Bankname { get; set; }
        public string Routingnumber { get; set; }
        public string Address { get; set; }
        public string Transitnumber { get; set; }
        public string City { get; set; }
        public string Accountnumber { get; set; }
        public int RegionId { get; set; }
        public int CurrentstatusId { get; set; }
        public string Postalcode { get; set; }
        public string Accountholdername { get; set; }
        public string Nickname { get; set; }
        public int Stackholdertypeid { get; set; }
        public string Bankaccountcontactname { get; set; }
        public string Phonenumber { get; set; }
        public string EmailAddress { get; set; }
        public string Entityname { get; set; }
        public string MailingAddress { get; set; }
        public string Entitycity { get; set; }
        public string Entityregion { get; set; }
        public string Entitypostalcode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int BankNameId { get; set; }
        public int IsDeleted { get; set; }
        public int Entityregionid { get; set; }
    }
}
