//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestockReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportJobLog
    {
        public int LogId { get; set; }
        public System.DateTime Jobtime { get; set; }
        public string Jobfunctionname { get; set; }
        public int Recordcount { get; set; }
        public string Status { get; set; }
        public int Soapserviceresponsetype { get; set; }
        public string ScheduleTime { get; set; }
        public System.DateTime ReportDate { get; set; }
    }
}
