//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestockReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTermsDetail
    {
        public int TermsDetailId { get; set; }
        public string TerminalKey { get; set; }
        public int VaultCashID { get; set; }
        public int SurchargeAccountCount { get; set; }
        public int InterchangeAccountCount { get; set; }
        public decimal Totalterminalsurchageamount { get; set; }
        public int SurchargesplitId1 { get; set; }
        public decimal Surchargesplitamount1 { get; set; }
        public int Surchargesettlementsource1 { get; set; }
        public int IsSurchargesegmented1 { get; set; }
        public int SurchargesegmentedID1 { get; set; }
        public int SurchargesplitId2 { get; set; }
        public decimal Surchargesplitamount2 { get; set; }
        public int Surchargesettlementsource2 { get; set; }
        public int IsSurchargesegmented2 { get; set; }
        public int SurchargesegmentedID2 { get; set; }
        public int SurchargesplitId3 { get; set; }
        public decimal Surchargesplitamount3 { get; set; }
        public int Surchargesettlementsource3 { get; set; }
        public int IsSurchargesegmented3 { get; set; }
        public int SurchargesegmentedID3 { get; set; }
        public int SurchargesplitId4 { get; set; }
        public decimal Surchargesplitamount4 { get; set; }
        public int Surchargesettlementsource4 { get; set; }
        public int IsSurchargesegmented4 { get; set; }
        public int SurchargesegmentedID4 { get; set; }
        public int SurchargesplitId5 { get; set; }
        public decimal Surchargesplitamount5 { get; set; }
        public int Surchargesettlementsource5 { get; set; }
        public int IsSurchargesegmented5 { get; set; }
        public int SurchargesegmentedID5 { get; set; }
        public decimal Totalsurchargeassigned { get; set; }
        public decimal TotalInterchangeAmount { get; set; }
        public string InterchangeSplitRemainder1 { get; set; }
        public decimal InterchangeSplitAmount1 { get; set; }
        public int InterchangeSplit2 { get; set; }
        public decimal InterchangeSplitAmount2 { get; set; }
        public int Interchangesettlementsource1 { get; set; }
        public int InterchangeSplit3 { get; set; }
        public decimal InterchangeSplitAmount3 { get; set; }
        public int Interchangesettlementsource2 { get; set; }
        public int InterchangeSplit4 { get; set; }
        public decimal InterchangeSplitAmount4 { get; set; }
        public int Interchangesettlementsource3 { get; set; }
        public int InterchangeSplit5 { get; set; }
        public decimal InterchangeSplitAmount5 { get; set; }
        public int Interchangesettlementsource4 { get; set; }
        public decimal TotalInterchangeassigned { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int InterchangeSplit1 { get; set; }
    }
}
