//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestockReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerminal
    {
        public int TerminalId { get; set; }
        public string TerminalKey { get; set; }
        public string LocationName { get; set; }
        public string LocationType { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string MakeAndModel { get; set; }
        public string SerialNumber { get; set; }
        public int IsActive { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Comment { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public int RelationshipId { get; set; }
        public int ProgramaTypeId { get; set; }
        public int CommunicationTypeId { get; set; }
        public string EmailAddress { get; set; }
        public decimal Surcharge { get; set; }
        public string CommunicationSerialNumber { get; set; }
    }
}
