//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestockReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerminalManager
    {
        public int TerminalManagerId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string TerminalId { get; set; }
        public string FundingType { get; set; }
        public string AccountName { get; set; }
        public string RoutingNumber { get; set; }
        public string TransitNumber { get; set; }
        public string AccountNumber { get; set; }
        public decimal DepositAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.DateTime SettlementDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ReportDate { get; set; }
    }
}
