//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestockReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerminalSurchargeAccount
    {
        public int SurchageId { get; set; }
        public string TerminalKey { get; set; }
        public string AccountHolder { get; set; }
        public string AccountRTA { get; set; }
        public string SplitType { get; set; }
        public double SplitAmount { get; set; }
        public string PaymentSchedule { get; set; }
        public int IsSurchargeAccount { get; set; }
        public int IsInterchangeAccount { get; set; }
    }
}
