//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestockReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int User_ID { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Email_Adress { get; set; }
        public bool IsActive { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Title { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int Province { get; set; }
        public string Postalcode { get; set; }
        public string Phonecell { get; set; }
        public string Phoneother { get; set; }
        public int RollAssigned { get; set; }
        public System.DateTime Create_Date { get; set; }
        public int Access_Level_ID { get; set; }
        public int IsDeleted { get; set; }
    }
}
