//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestockReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebmoonUser
    {
        public int User_ID { get; set; }
        public string WebmoonId { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
    }
}
